sudo: false

language: node_js

node_js:
  - "5.2.0"

before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - cd src && npm install
  - cd ..

script: npm test

branches:
  only:
    - master
